version: "3.9"


x-default: &default
  env_file: .env
  networks:
    - dockernet


services:
  app:
    <<: *default
    container_name: pf-app
    restart: always
    build: .
    command: yarn run start:dev
    ports:
      - "$PORT:$PORT"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis

  redis:
    <<: *default
    image: "redis:alpine"
    container_name: pf-redis
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: pf-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    healthcheck:
        disable: true
    ports:
      - "8081:8081"
    depends_on:
      - redis

  postgres:
    <<: *default
    image: postgres
    container_name: pf-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - data_postgres:/data/postgres
  pgadmin:
    <<: *default
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=patrick204nqh@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "8080:80"
    volumes:
      - data_pgadmin:/root/.pgadmin


  # es01:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
  #   container_name: es01
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es02,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data01:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - elastic
  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
  #   container_name: es02
  #   environment:
  #     - node.name=es02
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data02:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic
  # es03:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
  #   container_name: es03
  #   environment:
  #     - node.name=es03
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es02
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data03:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic


volumes:
  data_postgres: {}
  data_pgadmin: {}
  # data01:
  #   driver: local
  # data02:
  #   driver: local
  # data03:
  #   driver: local


networks:
  dockernet:
    driver: bridge
  # elastic:
  #   driver: bridge
